Initial implemetation of sqlalchemy orm
peopleAlreadyKnowWhoIAm/car-rent pull request #1
Opened 2024-05-04 21:27 UTC by peopleAlreadyKnowWhoIAm

2024-05-05 16:05 UTC, IgorBrat requested changes
Please look at suggestions and then merge.

2024-05-05 16:05 UTC, IgorBrat commented on requirements.txt
It's a good practice to put only libraries explicitely used in the project, not all the libraries installed along with them.

2024-05-05 16:05 UTC, IgorBrat commented on model/account.py
That's might be a good idea to add custom string representation for debugging purposes (for all models from the task).

2024-05-05 16:05 UTC, IgorBrat commented on main.py
Better to init and run app in method scope (if __name__ == "__main__"). But not mandatory,

2024-05-06 18:32 UTC, peopleAlreadyKnowWhoIAm commented on main.py
Changed

2024-05-06 18:33 UTC, peopleAlreadyKnowWhoIAm commented on model/account.py
Added in MappedAsDataclass as db.Model ancestor

2024-05-06 18:35 UTC, peopleAlreadyKnowWhoIAm commented on requirements.txt
Removed explicitly not required

2024-05-08 18:19 UTC, peopleAlreadyKnowWhoIAm commented
@IgorBrat  please resolve comments if ok

2024-05-08 18:22 UTC, IgorBrat approved these changes

2024-05-08 20:46 UTC, merged